server:
  port: 9527
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    sysmanage.serviceId: hrm-sysmanage 
    sysmanage.path: /sysmanage/** 
    course.serviceId: hrm-course 
    course.path: /course/** 
    fastdfs.serviceId: hrm-fastdfs 
    fastdfs.path: /common/** 
    es.serviceId: hrm-es 
    es.path: /es/**  
    staticpage.serviceId: hrm-staticpage 
    staticpage.path: /staticpage/**  
    rabbitmq.serviceId: hrm-rabbitmq
    rabbitmq.path: /rabbitmq/**     
  ignored-services: "*" 
  prefix: "/services" 
  retryable: true 
ribbon:
  ConnectTimeout: 250 
  ReadTimeout: 2000 
  OkToRetryOnAllOperations: true 
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000